# Generated by Django 4.1.7 on 2023-04-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210618_0224'),
        ('main', '0004_post_closed_post_state_alter_author_id_and_more'),
    ]

    operations = [
    ]
